import type { Metadata } from "next";
import { AppShell, AppShellHeader, Button, ColorSchemeScript, MantineProvider, mantineHtmlProps, DEFAULT_THEME, Text, Flex, AppShellMain } from "@mantine/core";
import '@mantine/core/styles.css';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <AppShell
            header={{ height: "52px" }}
          >
            <AppShellHeader px="xs">
              <Flex h="100%" align="center" justify="space-between">
                <Text size="md">AI School</Text>
                <Button>Get Started</Button>
              </Flex>
            </AppShellHeader>
            <AppShellMain>
              {children}
            </AppShellMain>
          </AppShell>


        </MantineProvider>
      </body>
    </html>
  )
}
