import type { Metadata } from "next";
import { AppShell, AppShellHeader, ColorSchemeScript, MantineProvider, mantineHtmlProps, Flex, AppShellMain, Image } from "@mantine/core";
import '@mantine/core/styles.css';
import AuthButton from "@/components/Auth/AuthButton";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <AppShell
            header={{ height: "52px" }}
          >
            <AppShellHeader px="xs">
              <Flex h="100%" align="center" justify="space-between">
                <Image src="/logo_export.svg" alt="logo_header" w={128}/>
                <AuthButton/>
              </Flex>
            </AppShellHeader>
            <AppShellMain>
              {children}
            </AppShellMain>
          </AppShell>


        </MantineProvider>
      </body>
    </html>
  )
}
